name: terraform-ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt
        run: terraform -chdir=infra/envs/baseline fmt -recursive -check

      - name: Terraform init
        run: terraform -chdir=infra/envs/baseline init -backend=false

      - name: Terraform validate
        run: terraform -chdir=infra/envs/baseline validate

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: TFLint
        run: tflint --chdir=infra/envs/baseline

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: tfsec
        run: tfsec infra

      - name: Install Checkov
        run: pip install checkov

      - name: Checkov
        run: checkov -d infra
